modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/collectibles/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="collectibles:loot_bag"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Collectibles.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/collectibles"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Every game these days has collectibles in it, this mod adds some to minecraft too. With a little bonus when you complete a set!'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

