modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/collectibles/issues"

[[mods]]
modId="collectibles"
version="1.1.6"
displayName="Collectibles"
itemIcon="collectibles:loot_bag"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Collectibles.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/collectibles"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
Every game these days has collectibles in it, this mod adds some to minecraft too. With a little bonus when you complete a set!
'''

[[dependencies.collectibles]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.collectibles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
