modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/collectibles/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="collectibles:loot_bag"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Collectibles/refs/heads/main/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/collectibles"
logoFile="logo.png"
credits="Leafe textures by Turtlessp"
authors="${mod_authors}"
description='''Every game these days has collectibles in it, this mod adds some to Minecraft too. With a little bonus when you complete a set!'''

[modproperties.${mod_id}]
configuredBackground="minecraft:textures/block/diamond_block.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="magmacore"
referralUrl="https://www.curseforge.com/minecraft/mc-mods/magma-core"
reason="Provides basic code and features such as update-checker"
type="required"
versionRange="${magmacore_version_range}"
ordering="AFTER"
side="BOTH"


